### ISSUE TITLE
View posts on home page

### ISSUE THREAD

**Issue by Sjwilhelms** [Sjwilhelms/BootChamp#1]
As a User

I can view posts by most recent

So that I can survey the sites content

AC1 multiple posts are displayed on home screen
AC2 user can sees titles, excerpts, preview
AC3 user can select a post to view in detail

**Comment by lkilu6456546** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added Post model, updated views to display posts on home page, and created a detail view for individual posts.

You can review changes in this commit: https://github.com/lkilu6456546/Sjwilhelms-BootChamp-1/commit/d933b3946d1fd4bc9227bb50498387d67c17eb95.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
